fizjorob/fizjocalendar/urls.py
from django.conf.urls import url
from . import views

app_name = 'fizjocalendar'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^/appointment/$', views.appointment, name='appointment'),
]

fizjorob/fizjorob/urls.py
from django.conf.urls import include,url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^fizjocalendar',include('fizjocalendar.urls'))
]

fizjorob/fizjocalendar/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Appointment(models.Model):
    name = models.CharField(max_length=40)
    surname = models.CharField(max_length=40)
    phone = models.CharField(max_length=12)
    age = models.IntegerField()
    time = models.TimeField()
    date = models.DateField()
    description = models.CharField(max_length=400)

fizjorob/fizjocalendar/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Appointment
from .modules.communication import EmailSender
def index(request):
    template = loader.get_template('fizjocalendar/index.html')
    return HttpResponse(template.render({}, request))

def appointment(request):
    newAppointment = Appointment( name = request.POST['name'],
                                  surname=request.POST['surname'],
                                  age = request.POST['age'],
                                  date = request.POST['date'],
                                  time = request.POST['time'],
                                  phone = request.POST['phone'],
                                  description = request.POST['description'])

    EmailSender.sendNewAppointmentEmail(newAppointment)
    appointmentSendTmpl = loader.get_template('fizjocalendar/appointment_send.html')
    return HttpResponse(appointmentSendTmpl.render({},request))

fizjorob/fizjocalendar/templates/fizjocalendar/appointment_send.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fizjo appointment</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'fizjocalendar/style.css' %}" />
</head>
<body>
<div class="jumbotron">
  <h3>Formularz kontaktowy</h3>
</div>
<div class="container" style="width: 25%">
<h4>Wiadomość o wizycie została przesłana</h4>
</div>
</body>
</html>

fizjorob/fizjocalendar/templates/fizjocalendar/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fizjo appointment</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'fizjocalendar/style.css' %}" />
</head>
<body>
<div class="jumbotron">
  <h3>Formularz kontaktowy</h3>
</div>
<div class="container" style="width: 25%">
<form action="{% url 'fizjocalendar:appointment' %}" method="post">
    {% csrf_token %}
    <label >Imie</label>
    <input type="text" class="form-control" name="name" />
    <label >Nazwisko</label>
    <input type="text" class="form-control" name="surname" />
    <label >Wiek</label>
    <input type="text" class="form-control" name="age" />
    <label >Data</label>
    <input type="date" class="form-control" name="date" />
    <label >Godzina</label>
    <input type="time" class="form-control" name="time" />
    <label >Nr telefonu</label>
    <input type="text" class="form-control" name="phone" />
    <label >Opis</label>
    <textarea class="form-control" rows="5" name="description" >Dodaj opis schorzenia</textarea>
<input type="submit" class="btn btn-default" value="Wyślij" />
</form>
</div>
</body>
</html>